apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: epic-road-trip
  title: Epic road trip
  description: Frontend de l'application Epic Road Trip
tags:
  - nodejs
  - vuejs
  - postgres
annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: group:ingenierie-logicielle
  providesApis: [epic-road-trip-api]

