version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - 8888:8081
    links: 
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

  front:
    build: 
      context: ./front
    ports:
      - 5173:5173
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules

  api:
    build: 
      context: ./api
    ports:
      - 8081:8081
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - postgres

volumes:
  local_pgdata:
