openapi: 3.0.2
info:
  title: WEB-800
  version: 1.0.0
  description: |
    An epitech project. We want to create some web vacation manager
servers:
  - url: "http://localhost:8081/"
paths:
  /sleep/{cityName}:
    get:
      parameters:
        - name: cityName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: fetchHotelsByCity
      description: Retrieves hotels by city from Overpass

  /enjoy/{cityName}:
    get:
      parameters:
        - name: cityName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: fetchActivitiesByCity
      description: Retrieves activities by city from Overpass

  /drink/{cityName}:
    get:
      parameters:
        - name: cityName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: fetchBarsByCity
      description: Retrieves bars by city from Overpass

  /travel/{cityName}:
    get:
      parameters:
        - name: cityName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: fetchTransportByCity
      description: Retrieves transport by city from Overpass

  /eat/{cityName}:
    get:
      parameters:
        - name: cityName
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: fetchRestaurantsByCity
      description: Retrieves restaurants by city from Overpass

  /history/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: addToHistory
      description: Adds to history

    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: getHistoryList
      description: Gets history list

  /favorite/{id}/{userId}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: addToFavorite
      description: Adds to favorites

    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: getFavoriteList
      description: Gets favorite list

  /trajet/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: addTrajet
      description: Adds trajet

    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
      operationId: getTrajetList
      description: Gets trajet list

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
