apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: epic-road-trip-front
  description: Frontend de l'application Epic Road Trip
spec:
  type: website
  lifecycle: experimental
  owner: epitech

