apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: epic-road-trip-api
  title: Epic Road Trip API
  description: Epic Road Trip api project NodeJS
spec:
  type: grpc
  owner: user:default/asanchez
  lifecycle: experimental
  dependOn:
    -component: epic-road-trip-web-app
  providedBy:
    -epic-road-trip-front
